FROM ubuntu

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get install -y python
RUN apt-get install -y git
RUN apt-get install -y pip
RUN git clone https://github.com/AyushBhardwaj321/face_mask_detection.git
WORKDIR /face_mask_detection
RUN pip install -r requirements.txt
CMD ["python","./detect_mask_video.py" 

