FROM ubuntu

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get install -y python
RUN apt-get install -y git
RUN apt-get install -y pip
RUN git clone https://github.com/AyushBhardwaj321/face-mask.git
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
COPY . /tmp/
WORKDIR /face-mask
CMD ["python3","detect_mask_photo.py"]
